### PR TITLE
Set up expo router

### PR DESCRIPTION
**Pull request by A-nirvana**
I've tried to add the expo router but it shows me the error "TypeError cannot read property 'isReady' of undefined : js engine hermes". I am sorry to say that I am unable to find the solution even after trying to find one for 5 days straight. I am eagerly waiting for your reply. Help me with this.
Screenshot (31)

### CODE REVIEW

**Comment by Arjun-G-04** [comment]
@A-nirvana hello, thanks for the PR, please ping me too in the description so that I get notified when you make a PR or update it. I will get back to you soon regarding this error.

**Comment by A-nirvana** [comment]
@Arjun-G-04 Okay, from the next time, I'll keep it in mind

**Comment by Arjun-G-04** [comment]
hello @A-nirvana, can you please provide steps to reproduce the bug you are facing?

**Comment by Arjun-G-04** [comment]
I feel it's better to take a step-by-step approach. Could you revert all your changes and first perform the steps given in this section: https://docs.expo.dev/router/installation/#manual-installation ?

**Comment by A-nirvana** [comment]
@Arjun-G-04 okay I'll do it. I'll restart
.

**Comment by Arjun-G-04** [comment]
cool, if you need more elaborate help, give us a ping in the [Discord server](https://discord.com/invite/V2DvAwEcjt)

**Comment by Arjun-G-04** [comment]
@A-nirvana any updates?

**Pull request closed without merging**
